name: sit-cosim
channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.12
  - pip

  - numpy
  - pandas
  - matplotlib
  - pyyaml
  - pyside6
  - packaging

  - geopandas
  - osmnx
  - shapely
  - pyproj
  - pyogrio
  - networkx
  - osmium-tool

  - pytorch=2.5.*
  - cpuonly

  - pip:
      - libcosimpy==0.0.5
      - pythonfmu==0.7.0
      - requests
      - ax-platform
