"""fmpy-backed reimplementation of the libcosimpy ``CoSimInstance``.

This mirrors the public API of the libcosimpy ``CoSimInstance`` but uses `fmpy`
as the underlying FMU engine. The motivation is that fmpy exposes
``fmi2Reset``/``reset`` on each FMU, which lets us add a working ``Reset()``
(the libcosimpy version cannot). Intended for use with FMUs generated by
``pythonfmu``.

Master algorithm: a simple fixed-step Jacobi scheme - read all connected outputs,
push them to the connected inputs, then step every FMU by one macro step.
"""

import sys
import shutil

import matplotlib.pyplot as plt
import numpy as np

from fmpy import extract, read_model_description, instantiate_fmu


class ObserverStruct:
    var = None
    var_type = None
    var_vr = None
    slave = None
    variable = None


class CoSimInstance:
    '''
        instanceName is the name of the co-simulation instance (str)
        stopTime is the stop time of the co-simulation (seconds)
        stepSize is the macro step size of the co-simulation (seconds)
    '''
    def __init__(self, instanceName: str = "simulation", stopTime: float = 1.0, stepSize: float = 0.01):
        self.instanceName = instanceName
        # Stored in SECONDS (fmpy doStep works in seconds), unlike the libcosimpy
        # implementation which converts to nanoseconds.
        self.stopTime = float(stopTime)
        self.stepSize = float(stepSize)
        self.time = 0.0

        self.observer_time_series_struct = {}
        self.observer_time_series_label = {}

        self.slaves = {}            # name -> {fmu, unzipdir, model_description}
        self.slaves_variables = {}  # name -> model_description.modelVariables

        self.slave_input_var = []
        self.slave_input_name = []

        self.slave_output_var = []
        self.slave_output_name = []

        self.first_plot = True

        self.fromExternalSlaveName = []
        self.fromExternalSlaveVar = []
        self.fromExternalSlaveFunc = []

        self.initial_values = {}  # (slaveName, slaveVar) -> value, re-applied on Reset
        self.initialized = False

    # ------------------------------------------------------------------
    # Variable lookup + type-aware get/set
    # ------------------------------------------------------------------
    def _get_variable(self, slaveName: str, variable: str):
        """Return ``(value_reference, type_str)`` for a variable.

        ``type_str`` is one of 'Real', 'Boolean', 'Integer', 'String'
        ('Enumeration' is treated as 'Integer').
        """
        for v in self.slaves_variables[slaveName]:
            if v.name == variable:
                vtype = v.type
                if vtype == "Enumeration":
                    vtype = "Integer"
                return v.valueReference, vtype
        raise Exception("Could not locate the variable %s in the model" % (variable))

    def GetVariableInfo(self, slaveName: str, variable: str):
        return self._get_variable(slaveName, variable)

    def _get_value(self, slaveName: str, variable: str):
        fmu = self.slaves[slaveName]["fmu"]
        vr, vtype = self._get_variable(slaveName, variable)
        if vtype == "Real":
            return fmu.getReal([vr])[0]
        if vtype == "Boolean":
            return bool(fmu.getBoolean([vr])[0])
        if vtype == "Integer":
            return fmu.getInteger([vr])[0]
        return fmu.getString([vr])[0]

    def _set_value(self, slaveName: str, variable: str, value):
        fmu = self.slaves[slaveName]["fmu"]
        vr, vtype = self._get_variable(slaveName, variable)
        if vtype == "Real":
            fmu.setReal([vr], [float(value)])
        elif vtype == "Boolean":
            fmu.setBoolean([vr], [bool(value)])
        elif vtype == "Integer":
            fmu.setInteger([vr], [int(value)])
        else:
            fmu.setString([vr], [str(value)])

    # ------------------------------------------------------------------
    # Observers
    # ------------------------------------------------------------------
    def AddObserverTimeSeries(self, name: str, slaveName: str, variable: str):
        try:
            obs = ObserverStruct()
            obs.slave = slaveName
            obs.var = variable
            obs.var_vr, obs.var_type = self._get_variable(slaveName, variable)
            obs.time = []
            obs.value = []
            self.observer_time_series_struct[name] = obs
        except Exception as error:
            print("An error occured while adding an observer: ", name, "-", slaveName, "-", variable, ": ", type(error).__name__, "-", error)
            sys.exit(1)

    def AddObserverTimeSeriesWithLabel(self, name: str, slaveName: str, variable: str, var_label: str = None):
        try:
            obs = ObserverStruct()
            obs.slave = slaveName
            obs.var = variable
            obs.var_vr, obs.var_type = self._get_variable(slaveName, variable)
            obs.time = []
            obs.value = []
            self.observer_time_series_struct[name] = obs
            self.observer_time_series_label[name] = var_label
        except Exception as error:
            print("An error occured while adding an observer: ", name, "-", slaveName, "-", variable, ": ", type(error).__name__, "-", error)
            sys.exit(1)

    def GetObserverTimeSeries(self, name: str, from_step: int = 1):
        try:
            obs = self.observer_time_series_struct[name]
            start_idx = max(from_step - 1, 0)
            time_seconds = list(obs.time[start_idx:])
            samples = np.array(obs.value[start_idx:])
            step_numbers = np.arange(start_idx + 1, start_idx + 1 + len(time_seconds))
            return time_seconds, step_numbers, samples
        except Exception as error:
            print("An error occured while obtaining a time series: ", name, " - ", type(error).__name__, "-", error)
            sys.exit(1)

    def PlotTimeSeries(self, separate_plots: bool = False, create_window: bool = True, create_title: bool = False, show: bool = True, legend: bool = True, show_instance_name: bool = False):
        for key in self.observer_time_series_struct:
            time_points, step_number, samples = self.GetObserverTimeSeries(key)
            if create_window:
                if self.first_plot:
                    plt.figure()
                    self.first_plot = False
                else:
                    if separate_plots:
                        plt.legend()
                        plt.grid()
                        plt.xlabel("Time [s]")
                        plt.ylabel(self.observer_time_series_label.get(key))
                        if create_title:
                            plt.title("Time series form co-simulation instance \"%s\"" % (self.instanceName))
                        plt.figure()

            label = str(key)
            if show_instance_name:
                label = self.instanceName + ": " + str(key)

            plt.plot(time_points, samples, label=label)
        if legend:
            plt.legend()
        plt.xlabel("Time [s]")
        plt.ylabel(self.observer_time_series_label.get(key))
        if create_title:
            plt.title("Time series form co-simulation instance \"%s\"" % (self.instanceName))
        plt.grid(True)
        if show:
            plt.show()

    def JoinPlotTimeSeries(self, key_group_list, create_title: bool = False, legend: bool = True, show_instance_name: bool = False, show_separately: bool = False, show=True):
        for key_group in key_group_list:
            struct_time_points = []
            struct_step_number = []
            struct_samples = []
            struct_lables = []

            for key in key_group:
                time_points, step_number, samples = self.GetObserverTimeSeries(key)
                struct_time_points.append(time_points)
                struct_step_number.append(step_number)
                struct_samples.append(samples)
                lable = str(key)
                if show_instance_name:
                    lable = self.instanceName + ": " + str(key)
                struct_lables.append(lable)

            plt.figure(figsize=(9, 7))
            for i in range(len(key_group)):
                plt.plot(struct_time_points[i], struct_samples[i], label=struct_lables[i])
            if legend:
                plt.legend(fontsize=8)
            plt.grid()
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.xlabel("Time [s]", fontsize=9)
            plt.ylabel(self.observer_time_series_label.get(key_group[0]), fontsize=9)
            if create_title:
                plt.title("Time series form co-simulation instance \"%s\"" % (self.instanceName))
            plt.tight_layout()
            if show_separately and show:
                plt.show()

        if not show_separately and show:
            plt.show()

    # ------------------------------------------------------------------
    # Slaves
    # ------------------------------------------------------------------
    def AddSlave(self, path: str, name: str):
        try:
            unzipdir = extract(path)
            model_description = read_model_description(unzipdir)
            fmu = instantiate_fmu(
                unzipdir=unzipdir,
                model_description=model_description,
                fmi_type="CoSimulation",
            )
            self.slaves[name] = {
                "fmu": fmu,
                "unzipdir": unzipdir,
                "model_description": model_description,
            }
            self.slaves_variables[name] = model_description.modelVariables
        except Exception as error:
            print("An error occured while adding a slave: ", name, "-", path, ": ", type(error).__name__, "-", error)
            sys.exit(1)

    def AddSlaveConnection(self, slaveInputName: str, slaveInputVar: str, slaveOutputName: str, slaveOutputVar: str):
        try:
            self.slave_input_name.append(slaveInputName)
            self.slave_input_var.append(slaveInputVar)
            self.slave_output_name.append(slaveOutputName)
            self.slave_output_var.append(slaveOutputVar)
        except Exception as error:
            print("An error occured while adding a connection: ", slaveInputName, ".", slaveInputVar, " = ", slaveOutputName, ".", slaveOutputVar, ": ", type(error).__name__, "-", error)
            sys.exit(1)

    def GetLastValue(self, slaveName: str, slaveVar: str):
        try:
            return self._get_value(slaveName, slaveVar)
        except Exception as error:
            print("An error occured while obtaing last value: ", slaveName, ".", slaveVar, ": ", type(error).__name__, "-", error)
            sys.exit(1)

    # ------------------------------------------------------------------
    # Manipulation
    # ------------------------------------------------------------------
    def CoSimManipulate(self):
        for i in range(0, len(self.slave_input_name)):
            try:
                out_vr, out_type = self._get_variable(self.slave_output_name[i], self.slave_output_var[i])
                in_vr, in_type = self._get_variable(self.slave_input_name[i], self.slave_input_var[i])
                if out_type == in_type:
                    out_val = self.GetLastValue(slaveName=self.slave_output_name[i], slaveVar=self.slave_output_var[i])
                    self._set_value(self.slave_input_name[i], self.slave_input_var[i], out_val)
            except Exception as error:
                print("An error occured during signal manipulation: ", self.slave_input_name[i], ".", self.slave_input_var[i], " = ", self.slave_output_name[i], ".", self.slave_output_var[i], " :", type(error).__name__, "-", error)
                sys.exit(1)

    def SingleVariableManipulation(self, slaveName: str, slaveVar: str, value):
        try:
            self._set_value(slaveName, slaveVar, value)
        except Exception as error:
            print("An error occured during single variable manipulation: ", slaveName, ".", slaveVar, " = ", value, ": ", type(error).__name__, "-", error)
            sys.exit(1)

    def AddInputFromExternal(self, slaveName: str, slaveVar: str, func):
        try:
            self.fromExternalSlaveName.append(slaveName)
            self.fromExternalSlaveVar.append(slaveVar)
            self.fromExternalSlaveFunc.append(func)
        except Exception as error:
            print("An error occured while setting an external input: ", slaveName, ".", slaveVar, ": ", type(error).__name__, "-", error)
            sys.exit(1)

    def SetInputFromExternal(self):
        for i in range(0, len(self.fromExternalSlaveName)):
            try:
                val = self.fromExternalSlaveFunc[i]()
                self._set_value(self.fromExternalSlaveName[i], self.fromExternalSlaveVar[i], val)
            except Exception as error:
                print("An error occured during signal manipulation from external: ", self.fromExternalSlaveName[i], ".", self.fromExternalSlaveVar[i], ": ", type(error).__name__, "-", error)
                sys.exit(1)

    # ------------------------------------------------------------------
    # Initial values
    # ------------------------------------------------------------------
    def SetInitialValue(self, slaveName: str, slaveVar: str, initValue):
        # Stored so Reset() can re-apply them. Applied to the FMU during
        # initialization (and immediately if already initialized).
        try:
            self.initial_values[(slaveName, slaveVar)] = initValue
            if self.initialized:
                self._set_value(slaveName, slaveVar, initValue)
        except Exception as error:
            print("An error occured while setting an initial value: ", slaveName, ".", slaveVar, " = ", initValue, ": ", type(error).__name__, "-", error)
            sys.exit(1)

    def SetInitialValues(self, slaveName: str, params: dict):
        for var_name, value in params.items():
            self.SetInitialValue(slaveName, var_name, value)

    def PreSolverFunctionCall(self):
        pass

    def PostSolverFunctionCall(self):
        pass

    # ------------------------------------------------------------------
    # Initialization / simulation / reset
    # ------------------------------------------------------------------
    def _initialize(self):
        """Bring every FMU from instantiated into stepping state."""
        if self.initialized:
            return
        for slave_data in self.slaves.values():
            slave_data["fmu"].setupExperiment(startTime=0.0, stopTime=self.stopTime)
        for slave_data in self.slaves.values():
            slave_data["fmu"].enterInitializationMode()
        for (slaveName, slaveVar), value in self.initial_values.items():
            self._set_value(slaveName, slaveVar, value)
        for slave_data in self.slaves.values():
            slave_data["fmu"].exitInitializationMode()
        self.initialized = True

    def Step(self):
        """Advance every FMU by one macro step and record observer samples.

        Does not mutate ``self.time`` itself - the caller (``Simulate()`` or a
        subclass's own stepping loop) owns time bookkeeping, exactly like the
        libcosimpy backend's ``self.execution.step()``. The observer sample is
        timestamped at ``self.time + self.stepSize`` (the time the FMU will
        hold immediately after this step) without writing that back.
        """
        self._initialize()
        # Source of problem
        for slave_data in self.slaves.values():
            
            slave_data["fmu"].doStep(
                currentCommunicationPoint=self.time,
                communicationStepSize=self.stepSize,
            )
        
        next_time = self.time + self.stepSize
        for obs in self.observer_time_series_struct.values():
            obs.time.append(next_time)
            obs.value.append(self._get_value(obs.slave, obs.var))

    def Simulate(self):
        self._initialize()

        n_steps = int(round(self.stopTime / self.stepSize))
        self.time = 0.0

        for _k in range(n_steps):
            self.CoSimManipulate()
            self.SetInputFromExternal()
            self.PreSolverFunctionCall()
            self.Step()
            self.PostSolverFunctionCall()
            self.time += self.stepSize

    def Reset(self):
        """Reset every FMU, clear recorded series, and re-apply initial values."""
        for slave_data in self.slaves.values():
            slave_data["fmu"].reset()
        self.initialized = False
        self.time = 0.0
        for obs in self.observer_time_series_struct.values():
            obs.time = []
            obs.value = []
        self._initialize()

    def Terminate(self):
        """Terminate FMUs and clean up the extracted directories."""
        for slave_data in self.slaves.values():
            fmu = slave_data["fmu"]
            try:
                fmu.terminate()
            except Exception:
                pass
            fmu.freeInstance()
            shutil.rmtree(slave_data["unzipdir"], ignore_errors=True)
